name: Tests

on: 
  pull_request: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Run all unit tests
      - name: Check all files into container
        run: ls -la

      - name: Go to the project directory
        working-directory: ./loaders.gl-showcases
        run: |
          yarn
          yarn test:nowatch
