name: Testing

# Controls when the workflow will run
on: 
  pull_request: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Run all unit tests
      - name: Running unit tests
        run: |
          cd loaders.gl-showcases
          yarn
          yarn test:nowatch

