name: Testing workflow

on: 
  pull_request: 
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i
        
      - name: Testing
        run: npm run test:nowatch
